#!/usr/bin/env bash
#displays "Best School" 10 times. On the 9th iteration,
#displays "Best school" then a new line.

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 8 ]
	then
		echo -e "Best school\nHi"
	else
		echo "Best School"
	fi
	(( count++ ))
done
