#!/usr/bin/env bash
#configure a ufw firewall to block all incoming traffic
#except for TCP ports 22, 80, and 443.

sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status
