#!/usr/bin/env bash

sudo systemctl stop nginx

sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx /var/www/html

sudo sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

sudo systemctl start nginx
