#!/usr/bin/env bash

# Stop Nginx if it's already running
sudo systemctl stop nginx

# Change the ownership of Nginx files and directories to nginx user
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx /var/www/html

# Update the Nginx configuration to run as nginx user and listen on port 8080
sudo sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl start nginx
