#!/usr/bin/env bash
if ! command -v nginx &> /dev/null
then
    apt-get update
    apt-get install -y nginx
fi
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart

